spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service

application:
  token:
    key: mirco@2024
    expire-time-access-token: 86400000
    expire-time-refresh-token: 86400000
